version: "3.8"
services: 
  pg:
    image: postgres:13.1-alpine
    volumes: 
      - pgdata:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: dockerpg
      POSTGRES_USER: dockerpg
      POSTGRES_DB: dockerpg  
    ports: 
      - '5432:5432'
  backend:
    build: ./
    ports:
      - '5001:5001'
    environment: 
      POSTGRES_PASSWORD: dockerpg
      POSTGRES_USER: dockerpg
      POSTGRES_DB: dockerpg 
    depends_on: 
      - pg
volumes: 
  pgdata:
